apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pcai-precheck.fullname" . }}-domains
  labels:
    {{- include "pcai-precheck.labels" . | nindent 4 }}
data:
  domains.txt: |
    {{- range .Values.precheck.domains }}
    {{ . }}
    {{- end }}
